### ISSUE TITLE
minified with gulp-uglify incorrectly 

### ISSUE THREAD

**Issue by fantomfield** [simonbengtsson/jsPDF-AutoTable#172] opened 2016-09-19 16:46 UTC
When minified 2.0.34 using gulp-uglify@1.5.4, Code is incorrectly minified.

minifed code causing exception:

```
 var n = a.cells[t.dataKey];
```

(middleLine causing exception to be thrown)

unminifed code causing exception:
https://github.com/simonbengtsson/jsPDF-AutoTable/blame/master/src/main.js#L341

minified correctly using 2.0.26

**Comment by fantomfield** [comment] 2016-09-19 17:06
minified function 2.0.26 working
`
t.forEach(function(e, t) {
            var r = new v(e)
              , i = t % 2 === 0
              , a = M.styles([C[S.theme].table, i ? C[S.theme].alternateRow : {}])
              , o = Object.assign({}, S.styles, S.bodyStyles, i ? S.alternateRowStyles : {});
            r.styles = Object.assign({}, a, o),
            r.index = t,
            L.columns.forEach(function(t) {
                var i = new b;
                i.raw = e[t.dataKey],
                i.styles = Object.assign({}, r.styles, t.styles),
                i.text = "undefined" != typeof i.raw ? "" + i.raw : "",
                r.cells[t.dataKey] = i,
                S.createdCell(i, p({
                    column: t,
                    row: r
                })),
                i.contentWidth = 2 * i.styles.cellPadding + f(i.text, i.styles),
                i.text = i.text.split(n)
            }),
            L.rows.push(r)
        })
    }
`

minified function 2.0.34 (throws exception)

`
u.forEach(function(t, n) {
            var r = 0;
            gr.columns.forEach(function(t) {
                var n = a.cells[t.dataKey];
                f(n.styles);
                var i = t.width - 2 * n.styles.cellPadding;
                if ("linebreak" === n.styles.overflow)
                    try {
                        n.text = e.splitTextToSize(n.text, i + 1, {
                            fontSize: n.styles.fontSize
                        })
                    } catch (a) {
                        if (!(a instanceof TypeError && Array.isArray(n.text)))
                            throw a;
                        n.text = e.splitTextToSize(n.text.join(" "), i + 1, {
                            fontSize: n.styles.fontSize
                        })
                    }
                else
                    "ellipsize" === n.styles.overflow ? n.text = m(n.text, i, n.styles) : "visible" === n.styles.overflow || ("hidden" === n.styles.overflow ? n.text = m(n.text, i, n.styles, "") : "function" == typeof n.styles.overflow ? n.text = n.styles.overflow(n.text, i) : console.error("Unrecognized overflow type: " + n.styles.overflow));
                var o = Array.isArray(n.text) ? n.text.length - 1 : 0;
                o > r && (r = o)
            }),
            t.heightStyle = t.styles.rowHeight,
            t.height = t.heightStyle + r * t.styles.fontSize * E,
            gr.height += t.height
        })
    }
`

**Comment by simonbengtsson** [comment] 2016-09-19 17:07
What kind of exception?

**Comment by fantomfield** [comment] 2016-09-20 15:59
TypeError: Cannot read property '0' of undefined

**Comment by simonbengtsson** [comment] 2016-09-24 13:10
Tried with both `gulp-uglify` version 1.5.3 and 2.0.0 and both works for me. It would be great if you could provide more information about how to reproduce this issue.

**Comment by simonbengtsson** [comment] 2016-10-06 01:30
Feel free to reopen the issue with more information if you are still seeing it. Closing for now since I couldn't reproduce.

**Comment by KerstenDoering** [comment] 2016-12-20 10:59
Could you please reopen this issue?

Error "Cannot read property '0' of undefined" could be reproduced with "grunt-contrib-uglify": "~0.2.0" and was solved so far with "grunt-contrib-uglify": "0.9.1" and uglify: { options: { mangle: false } 	}. The standard example pdf.autoTable(columns, data) was used with bower.json "jspdf-autotable": "2.1.0".

Everything worked fine without uglification.

**Comment by simonbengtsson** [comment] 2016-12-21 19:55
`grunt-contrib-uglify 0.2.0` is more than three years old? If you are having the same issue with version `>2.0` please create a new issue with more information.

**Closed by simonbengtsson** 2016-12-21 19:55 UTC

**Comment by orunjubd** [comment] 2017-04-18 05:52
<script src="../js/FileSaver.min.js" type="text/javascript"></script> 
    <script src="../js/xlsx.core.min.js" type="text/javascript"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.min.js" type="text/javascript"></script>
    <script src="../js/jspdf.plugin.autotable.js" type="text/javascript"></script>
    <script src="../js/html2canvas.min.js" type="text/javascript"></script>    
    <script src="../js/tableExport.js" type="text/javascript"></script>         

I face a lot of error: some are - [version: 2.3.0]

* * the afterPageContent, beforePageContent and afterPageAdd hooks are deprecated. Use addPageContent instead
** Use of deprecated style: rowHeight, use vertical cell padding instead
** jspdf.plugin.autotable.js:1163 Deprecation warning: Use dataKey instead of key

I replace all code your exception way.

But rest of 2 error can't understand how can I solve it -

** console.error("Unrecognized overflow type: " + cell.styles.overflow);
** console.log(doc.internal.getFontSize());  ===== ( its output 16)
** tableExport.js:859 Uncaught TypeError: Cannot read property 'fontSize' of undefined

Any help?
