### ISSUE TITLE
Footer Overlapping -Margin Bottom

### ISSUE THREAD

**Issue by omkargudekar** [simonbengtsson/jsPDF-AutoTable#257] opened 2017-04-27 02:43 UTC
Hello,

I encountered situation where margin bottom is not always respected. 

Please find below screennshots.

## Perfectly working for Page 1

<img width="862" alt="screen shot 2017-04-26 at 7 39 42 pm" src="https://cloud.githubusercontent.com/assets/8680483/25465644/4fb7fdde-2ab8-11e7-898f-bec3741378e9.png">

## Overlapping on Page 4

<img width="903" alt="screen shot 2017-04-26 at 7 39 25 pm" src="https://cloud.githubusercontent.com/assets/8680483/25465633/3b6610e6-2ab8-11e7-8736-61413957580e.png">

**Comment by simonbengtsson** [comment] 2017-05-29 06:24
Seems like a bug indeed. Could you post the code you were using as well?

**Comment by omkargudekar** [comment] 2017-06-07 23:58
[JSPDFBug.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/1059613/JSPDFBug.zip)

Sorry for late reply. It took me while to replicate scenario. 

Please find attached code.

Please run the code, **and check Page number 12, 19**

**Comment by omkargudekar** [comment] 2017-07-07 18:08
Hi,
Did you get chance to look at the bug ?

**Comment by GenaDos** [comment] 2017-08-02 14:42
Hi All,

I have the same issue.
The problem appears when one of the cells has wrapped text (takes more then one row in cell),  and of course it is not single page report (and it is not on first page in my variant it is on 7-th).
@simonbengtsson do you have any temporary propose to resolve this issue ?

Thank you.

**Comment by GenaDos** [comment] 2017-08-04 06:35
The problem is in the this part of the source code.
{code}
// Modify the row to fit the current page and calculate text and height of partial row
                    row.spansMultiplePages = true;
                    var pageHeight = table.doc.internal.pageSize.height();
                    var maxCellHeight = 0;
                    var remainingLineCount;
                    for (var j = 0; j < table.columns.length; j++) {
                        var col = table.columns[j];
                        var cell = row.cells[col.dataKey];
                        var fontHeight = cell.styles.fontSize / config_1.Config.scaleFactor() * config_1.FONT_ROW_RATIO;
                        var vPadding = cell.padding('vertical');
                        var remainingPageSpace = pageHeight - table.cursor.y - table.margin('bottom');
                        **remainingLineCount = Math.floor((remainingPageSpace - vPadding) / fontHeight);**
                        if (Array.isArray(cell.text) && cell.text.length > remainingLineCount) {
                       var remainingLines = cell.text.splice(remainingLineCount, cell.text.length);
{code}

When "remainingPageSpace" is less then "vPadding" (cell height) then remainingLineCount start to be -1 and remainingLines  returns wrong text which in end add wrong row on page.

So, in my solution upper on level of add page I add "isRemainingCellHeigth(table,row)".
{code}
 if (row.maxLineCount <= 1 || isRemainingCellHeigth(table,row) == false) {
                    common_1.addPage();
                }
{code}
I add additional function isRemainingCellHeigth which check if remaining space enough for cell with value.
{code}
function isRemainingCellHeight(table, row) {
            for (var j = 0; j < table.columns.length; j++) {
                var col = table.columns[j];
                var cell = row.cells[col.dataKey];
                var pageHeight = table.doc.internal.pageSize.height();
                var vPadding = cell.padding('vertical');
                var remainingPageSpace = pageHeight - table.cursor.y - table.margin('bottom');
                if (remainingPageSpace - vPadding <= 0) {
                    return false;
                }                
            }
            return true;            
        }
{code}

Or you can check it in main cycle and "break" row when not enough space.

**Comment by simonbengtsson** [comment] 2018-08-04 13:27
Duplicate of #370

**Closed by simonbengtsson** 2018-08-04 13:27 UTC
