### ISSUE TITLE
Some columns are shrinked because of large texts in some columns

### ISSUE THREAD

**Issue by urenpatelce** [simonbengtsson/jsPDF-AutoTable#1061] opened 2024-06-25 09:02 UTC
We observed that when there are more than 10 columns and if any 1 or 2 columns are having big text which is not having any whitespace like GUID or InstanceID then some columns are getting very little space to render the content and the side effect is large size report and unusable as well. Please check the screenshot below:

![image](https://github.com/simonbengtsson/jsPDF-AutoTable/assets/33483635/95544ee9-113b-4682-a9ed-ebb394e76ab9)

**Comment by urenpatelce** [comment] 2024-06-25 09:03
I think with dynamic or automatic scaling as well, some min width should be given to each column automatically.

**Comment by mmghv** [comment] 2024-06-25 15:00
Duplicate of #1018

This should be fixed by #1053 in the unreleased v4 branch, you can test it out yourself or if you provide a reproducible example I could test it locally and share the results.

Although in the attached screenshot I don't see any single long-text column, maybe the content is too much for this size, nonetheless, I'm curious to see the effect of the new algorithm.

**Closed** 2024-07-01 23:31 UTC
