### ISSUE TITLE
AutoTable Misaligning Text when Overflow is set to Linebreak

### ISSUE THREAD

**Issue by JosephUrciuoli** [simonbengtsson/jsPDF-AutoTable#66] opened 2015-09-15 18:43 UTC
![image](https://cloud.githubusercontent.com/assets/6527023/9886424/48a8cf12-5bb8-11e5-9f8c-fc55ca043319.png)

I am using autotable to generate the above tables.  Everything aligns perfectly until text comes around that has multiple lines, at which point the left margin gets misaligned.  Is there any fix for this issue?

**Comment by simonbengtsson** [comment] 2015-09-15 19:09
Take a look at the `Long text` example in `examples.js` and see if you can make it work. I have had no issues with alignment of multi line cells. If you are still having problems after that you can create a codepen that reproduces this. You can fork this codepen to make it quicker http://codepen.io/someatoms/pen/EjwPEb?editors=001

**Comment by simonbengtsson** [comment] 2015-10-19 16:03
Closing this as I couldn't reproduce it. Feel free to reopen with more information if you are still experience the issue.

**Closed by simonbengtsson** 2015-10-19 16:03 UTC
