### ISSUE TITLE
Multiple tables example: Table breaking to 3rd page in the example provided

### ISSUE THREAD

**Issue by codesmith21** [simonbengtsson/jsPDF-AutoTable#253] opened 2017-04-13 12:22 UTC
Hi Folks,

Great work on this project! :)

I am facing an issue while working with multiple tables example. Some of the rows from 'bottom left' and 'bottom right' tables are coming up in page 1 which is perfect. In 2nd page the remaining rows from 'bottom left' table are just getting displayed and the remaining rows of 'bottom right' table are coming up in 3rd page, which is unwanted. I need to display the remaining records from both the bottom one tables side-by-side in the 2nd page.

Requesting your help. Thanks in advance.

**Comment by simonbengtsson** [comment] 2017-05-29 06:28
In the multiple tables it should be an example of this? Otherwise I'm not sure what you mean. Can you provide some code?

**Comment by Rwothoromo** [comment] 2017-12-20 08:26
Hi, I am having the same problem when working with tables having a lot of data.

For example:


`
<script type="text/javascript">
    $(document).ready(function () {
        $("#dopdf").click(function () { //print button clicked
            doc.text(40, 90, "DRUGS");
            var startingPage = doc.internal.getCurrentPageInfo().pageNumber;

            doc.setPage(startingPage);
            var res = doc.autoTableHtmlToJson(document.getElementById("drugs1"));
            doc.autoTable(res.columns, res.data, { theme: 'striped', startY: 100, pagebreak: 'avoid',
                margin: {right: 550},
                styles: {cellPadding: 6, overflow: 'linebreak'},
                headerStyles: {rowHeight: 15, fontSize: 9, valign: 'middle', fillColor: [102, 162, 102]},
                bodyStyles: {rowHeight: 12, fontSize: 9, valign: 'middle'}
                });
            
            doc.setPage(startingPage);
            var res = doc.autoTableHtmlToJson(document.getElementById("drugs2"));
            doc.autoTable(res.columns, res.data, { theme: 'striped', startY: 100, pagebreak: 'avoid',
                margin: {left: 300, right: 300},
                styles: {cellPadding: 6, overflow: 'linebreak'},
                headerStyles: {rowHeight: 15, fontSize: 9, valign: 'middle', fillColor: [102, 162, 102]},
                bodyStyles: {rowHeight: 12, fontSize: 9, valign: 'middle'}
                });
            
            doc.setPage(startingPage);
            var res = doc.autoTableHtmlToJson(document.getElementById("drugs3"));
            doc.autoTable(res.columns, res.data, { theme: 'striped', startY: 100, pagebreak: 'avoid',
                margin: {left: 550},
                styles: {cellPadding: 6, overflow: 'linebreak'},
                headerStyles: {rowHeight: 15, fontSize: 9, valign: 'middle', fillColor: [102, 162, 102]},
                bodyStyles: {rowHeight: 12, fontSize: 9, valign: 'middle'}
            });
            doc.output("dataurlnewwindow");
        });
    });
</script>

`

**Comment by simonbengtsson** [comment] 2018-08-04 13:29
I think this is a duplicate of #370

**Closed by simonbengtsson** 2018-08-04 13:29 UTC

**Comment by manishuk03** [comment] 2020-09-16 08:08
downloadPDFFile(){
        var doc = new jsPDF("landscape");
        doc.autoTable({html:"#exportarticleTable"});
        doc.autoTable({html:"#exportsectionTable"});
        doc.autoTable({html:"#exportnewsletterTable"});
        doc.autoTable({html:"#exportotherproductTable"});
        doc.autoTable({html:"#exportfrontpageTable"});
        doc.save('myPDF.pdf');
 }
