### ISSUE TITLE
Bug: "display:none" element is visible in a PDF generated with IE11.

### ISSUE THREAD

**Issue by cedriccharles4** [simonbengtsson/jsPDF-AutoTable#505] opened 2019-06-12 10:01 UTC
Hello there :) !
I have a problem, only with IE11. In my table, I have an autocomplete input field. When I type something in that field, it gives me a list of choices. When I've made my choice, the list is hidden with a display:none. But when I download the PDF in IE11 (only with IE11), that list is visible. Not with other browsers.
PDF generated with IE 11 (not ok): https://snag.gy/zAKwdq.jpg
PDF generated with Chrome (ok): https://snag.gy/9p4lE5.jpg

You can try this there : https://noel-marquet.be/en/glue-consumption/

Here is the HTML code generated just before I hit the "Save as PDF" button: 
![image](https://user-images.githubusercontent.com/5189652/59342243-adb43000-8d09-11e9-95d8-437ba98b0e07.png)

The code for autotable is:
```
var doc = new jsPDF(),
			numberLine = $('#calculator tr').length;
		//console.log(numberLine);
	    // You can use html:
	    doc.autoTable({
		    headStyles: {
			    textColor: [32, 33, 36],
			    fontSize: 8,
			    cellPadding: 4,
			    halign: 'center',
			},
			footStyles: {
			    fillColor: [255, 255, 255],
			    textColor: [32, 33, 36],
			    fontStyle: 'bold',
			    fontSize: 8,
			    cellPadding: 4,
			},
			bodyStyles: {
			    fillColor: [255, 255, 255],
			    textColor: [32, 33, 36],
			    fontStyle: 'normal',
			    fontSize: 8,
			    cellPadding: 4,
			    halign: 'center',
			},
			alternateRowStyles: {
				fillColor: [247, 247, 247],
			    textColor: [32, 33, 36],
			    fontStyle: 'normal',
			    fontSize: 8,
			    cellPadding: 4,
			},
		    html: '#calculator',
			includeHiddenHtml: false,
		    didParseCell: function(HookData) {
				if (HookData.row.section == 'head') {
					if(HookData.row.index == 0) {
						HookData.cell.styles.fillColor = [231, 231, 228];
					} else {
						HookData.cell.styles.fillColor = [220, 220, 220];
					}
					HookData.cell.styles.lineColor = [197, 197, 197];
					HookData.cell.styles.lineWidth = 0.2;
				} else if (HookData.row.section == 'foot') {
					
				} else if (HookData.row.section == 'body') {
					HookData.cell.styles.lineColor = [197, 197, 197];
					HookData.cell.styles.lineWidth = 0.2;
										
					if(HookData.column.dataKey == 2 || HookData.column.dataKey == 3 || HookData.column.dataKey == 4 || HookData.column.dataKey == 5 ) {

					} else if (HookData.column.dataKey == 1) {
						var newValue = new Array(HookData.cell.text.join(' '));
						HookData.cell.text = newValue;
					}
				}	
			},
		});
	    
	    doc.save('glue-calculator.pdf');
```

Thank you in advance,
Cedric

**Comment by simonbengtsson** [comment] 2019-06-12 11:53
I'm almost more surprised about chrome hiding those elements... Can you check the logic of `htmlParser.ts` and see if you can find something there?

**Comment by cedriccharles4** [comment] 2019-06-12 12:04
Chrome is not the only one. Chrome Firefox Safari and Edge are hiding the elements (because they have a "display:none" I guess)...Only IE11 having the issue to show those display:none elements.

**Comment by simonbengtsson** [comment] 2019-06-12 12:08
In `htmlParser.ts` there is a simple check if the `td` cell is hidden or visible. So I would have thought that chrome would show the list as well (since you put the `display: none` on the `ul` element and not the parent `td` element.

**Comment by cedriccharles4** [comment] 2019-06-12 12:18
Maybe the PDF generation in Chrome/Safari/Firefox/Edge are understanding the display:none tag ?

**Comment by simonbengtsson** [comment] 2019-06-12 12:19
But `htmlParser.ts` only check display:none for `td` elements, not `ul` 😕

**Comment by cedriccharles4** [comment] 2019-06-12 12:31
Yes...

**Comment by cedriccharles4** [comment] 2019-06-13 14:05
Have you been able to eventually reproduce this?

**Comment by simonbengtsson** [comment] 2019-06-18 05:52
I don't have a way to test with IE 11, but if you find the issue I'll merge a PR right way.

**Comment by simonbengtsson** [comment] 2019-07-10 21:05
The library will only check the visiblity of the td elements, not elements inside of those. So will close this as kind of not a bug.

**Closed by simonbengtsson** 2019-07-10 21:05 UTC
Labels: bug, help wanted
