### ISSUE TITLE
limit amount of columns per a page

### ISSUE THREAD

**Issue by jamessuske** [simonbengtsson/jsPDF-AutoTable#321] opened 2018-02-01 17:27 UTC
Hi,

I have a very long table and it gets cut off, I am looking for away to do a page break after a certain amount of rows. Here is what I got:

```
var doc = new jsPDF('l', 'mm', "a0");
        var tbl = $('#red-blue-table').clone();
        var res = doc.autoTableHtmlToJson(tbl.get(0));

        doc.autoTable(res.columns, res.data, {
            startY: 40,
            pageBreak: 'auto',
            margin: {
                top: 40
            },
            addPageContent: function (data) {
                doc.setFontSize(28);
                doc.setTextColor(0);
                doc.setFontStyle('bold');
                doc.text("Production Report " + $("#dropdown").val(), 500, 30);
            },
            styles: {
                fontSize: 20,
                overflow: 'linebreak',
                columnWidth: 'wrap',
            },
            drawCell: function (cell, data) {
                /*if (row.index > 0 && row.index % 20 === 0) {
                    doc.autoTableAddPage();
                }*/
            },
            theme: 'grid'
        });

        doc.save("Report.pdf");
```

Here is a screen shot of my issue....

<img width="193" alt="screen shot 2018-02-01 at 12 26 18 pm" src="https://user-images.githubusercontent.com/8172382/35693102-22ef5534-074b-11e8-9d6a-973575c1c52e.png">

**Comment by simonbengtsson** [comment] 2018-08-04 12:40
Would you simply want to print remaining columns on a new page or how would you want the table to look?

**Comment by simonbengtsson** [comment] 2018-08-04 12:58
I think this is a duplicate of #307

**Closed by simonbengtsson** 2018-08-04 12:58 UTC
Labels: enhancement
