### ISSUE TITLE
JSPDF Autotable breaks rows

### ISSUE THREAD

**Issue by panagulis72** [simonbengtsson/jsPDF-AutoTable#283] opened 2017-09-03 10:14 UTC
The problem is that the data will be dynamic (I'm going to use AngularJS 1.x) and so the rows can have differents height.

In some cases, Autotable breaks the last row of the page, continuing to the next one. How can I prevent this behavior, and set up Autotable to take the last row (which default would break) and bring it to the next page?

This is my code: https://jsfiddle.net/9vgxvfkh/1/

P.S.: The margin top on the header is because then I will add an image.

**Comment by davidhockey22** [comment] 2017-10-12 15:22
Look at the V3 branch and you'll see the author has created an option in it to avoid breaking a row up. This would fix your issue, but has not been released yet. I am dealing with the same problem.

**Comment by paddotk** [comment] 2017-11-02 14:53
Is V3 still in beta? It's not available through Bower at least.

**Comment by MANUVILAKUNNATHU** [comment] 2018-05-08 07:02
Unfortunately we cant able to achieve this by using some styles or setting parameters.
but i just partially solved this problem by modifying the jspdf autotable source code.In the source code 'jspdf.plugin.autotable.js' file contain a method named 'printFullRow',this method is called for each row after this there is a check if the row can fit on the page.if row cannot fit then there is a check how many lines of text  does it contains.So just change the checking to a bigger number to avoid the page break issues.for example
change the code from ' if (row.maxLineCount <= 1) ' to ' if (row.maxLineCount <= 50) '.
Unless 50 lines can't fit on page.

**Comment by simonbengtsson** [comment] 2018-08-04 13:16
Duplicate of #370

**Closed by simonbengtsson** 2018-08-04 13:16 UTC
