### ISSUE TITLE
Altering cell text in createdCell hook breaks table style

### ISSUE THREAD

**Issue by Mario-Eis** [simonbengtsson/jsPDF-AutoTable#227] opened 2017-01-18 20:37 UTC
As you can see in the generated pdf, the text in the first column breaks in the middle of words. This happens, because the text of the cell in the last column gets altered in the createdCell hook. This is done to add the currency, because the service responds an integer value like 12000 and not text with the currency already attached. Seems to be a bug to me. Or maybe i did not understand how to "style" text. Is the createdCell hook the wrong place to do that?

I added a plunker as there seems to be a defect with the suggested codepen:
https://plnkr.co/edit/SI1X4D2myWwzArH9JrPO?p=preview

off-topic: as you can see in the plunker, there is always the need to do 
```
// prevent 'null' as text in table columns
if (!cell.raw) {
  cell.text = '';
}
```
in the createdCell hook because otherwise a null value would be rendered as text 'null'. Maybe it would be a small cosmetic feature to automate this.

oh and also note the console output in the latest version. think there is a lost console.log somewhere in the code :)

**Comment by simonbengtsson** [comment] 2017-01-18 20:49
To me it seems to be expected behavior since you are using `overflow: linebreak;` together with the default `columnWidth: auto;` on the name column? You can try setting the column style of the name column to wrap which will result in the following:

![screen shot 2017-01-18 at 21 47 37](https://cloud.githubusercontent.com/assets/3586691/22082411/f66a9940-ddc7-11e6-8029-e736cefda558.png)


Thanks for the other comments btw! I fixed so that null is now printed as empty string and removed the extraneous log.

**Comment by Mario-Eis** [comment] 2017-01-18 21:03
Yes, wrap works fine. I also tried that. But the 'name' column can get long as well. So it needs to break. 'linebreak' also works. But it breaks in the middle of the word. Also in the column header. Maybe its just by coincidence, but if there is no text modification in the last column, its breaks between the words.

My current workaround is to simply modify the items. Unfortunately I need to copy the whole dataset to do this because it's bound to a angular view. And modifying the original one would break the view on the page.

Is it intended to break in the middle of words or between words?

**Comment by Mario-Eis** [comment] 2017-01-18 21:08
Oh, you are right. Seems to me that was by coincidence. Adding the currency to the items also breaks the words. So its intended to break words? Is there a way to keep the header as a whole words? Like 'wrap' only on the header? Tried that, but didn't seem to work.
Or maybe a way to break between words?

**Comment by simonbengtsson** [comment] 2017-01-18 21:27
Interesting! I thought it never split words, but seems like I was wrong. Made some tests now and seems like the built in jspdf method `splitTextToSize` which I am using to split the text is splitting the words if necessary.

**Comment by simonbengtsson** [comment] 2017-01-18 21:29
Will look further into a work around for this tomorrow. Should be possible to make a temporary fix by measuring the text yourself and conditionally set a columnWidth on the column in the createdCell if certain conditions are true.

**Comment by simonbengtsson** [comment] 2017-01-29 15:34
Added support for setting individual cell widths now. This is done by setting the style `minCellWidth`. It replaces the `columnWidth` style. This means that you would be able to set for example `minCellWidth: 'wrap'` for header cells while keep `minCellWidth: 'auto'` for body cells. This will be released in the upcoming version 3.

**Closed by simonbengtsson** 2017-01-29 15:34 UTC

**Comment by Mario-Eis** [comment] 2017-01-30 17:12
Great work! I think a minCellWidth could also be a great idea to avoid splitting words.

**Comment by Mario-Eis** [comment] 2017-05-21 17:25
Will there be an update on npm including the log issue mentioned above? Unfortunately it spams my log files :( (my app is running in a native CEF container and keeps the log on disk for debugging).

**Comment by erenustun** [comment] 2019-08-08 09:27
> To me it seems to be expected behavior since you are using `overflow: linebreak;` together with the default `columnWidth: auto;` on the name column? You can try setting the column style of the name column to wrap which will result in the following:
> 
> ![screen shot 2017-01-18 at 21 47 37](https://cloud.githubusercontent.com/assets/3586691/22082411/f66a9940-ddc7-11e6-8029-e736cefda558.png)
> 
> Thanks for the other comments btw! I fixed so that null is now printed as empty string and removed the extraneous log.

Hey,

How did you align the Preis th to the right?

I know it's been 2 years, maybe something changed in codebase.

Thanks.
