### ISSUE TITLE
First page is blank when dataset is large and compression is true

### ISSUE THREAD

**Issue by Primith** [simonbengtsson/jsPDF-AutoTable#598] opened 2020-02-17 07:50 UTC
When data is large and compression is true on jspdf, the first page is blank.

For example, just modify the content example like this : 
line 112 `var doc = new jsPDF({compress: true})`
line 127 `body: bodyRows(20000),`

Download the pdf (the preview doesn't work) and you'll see the first blank page.

Seems similar to #365

**Comment by simonbengtsson** [comment] 2020-02-17 12:10
When trying 20000 rows the entire page freezes for me. 15000 rows seems to work fine.

**Comment by simonbengtsson** [comment] 2020-03-24 23:40
The embedded files works poorly with many rows. Tried now with the simple.html example instead with 100000 rows. Seems to work fine without issues with first page or when compress is true. Can you reproduce outside of the embedded example? If so can you provide an example?

**Comment by Primith** [comment] 2020-03-30 06:06
Hello, 

Thanks for your time on this issue.

I reproduced issue with 20 000 rows in simple.html with the following steps : 
Comment line : doc.autoTable({html: '#table'});
Line 55 : var doc = new jsPDF({compress: true});
Copy line 61 * 20 000 times.

With this configuration, the first page is blank. 

I tried to create an issue branch to show you but permissions denied.

**Comment by Primith** [comment] 2020-04-07 07:14
Hello, 

Can you reopen this issue please ? It's not a question but a bug. 

Thanks.

**Comment by mmghv** [comment] 2020-04-07 14:33
I did some debugging, it turned out to be a `jsPDF` bug.
It happens when `compress` option is `true` and applying some styles a large amount of times on a single page it causes the page to be blank.

Here's a [codepen](https://codepen.io/mmghv/pen/ZEGgZpa?editors=1010) reproducing the problem.
When applying `setFillColor()` 300,000 times it causes the page to be blank.

The problem seems to be fixed in the latest version, but this version is not tagged as a release and it has its own bugs, like the one discussed is issue #620

Although, this could be avoided to some extent by not applying unuseful color styles when calculating cell widths in `fitContent()` method, which could also make the plugin a little bit faster with large dataset.

**Comment by simonbengtsson** [comment] 2020-04-08 06:56
Interesting for sure! Let's hope they release the new version soon.

**Closed** 2020-04-09 14:28 UTC
Labels: bug, jsPDF

**Comment by Primith** [comment] 2020-04-09 14:33
Thanks to both of you for the correction.
