### ISSUE TITLE
Issue with a table that has a rowspan bigger than 50

### ISSUE THREAD

**Issue by juniorutu** [simonbengtsson/jsPDF-AutoTable#446] opened 2019-02-03 16:11 UTC
Hello,

I have a table that has more than 1000 rows.
Some rows have rowspan > 50
Because of this when i try to generate the table i get the following error "Cannot set property 'height' of undefined".
If i set the property 'pageBreak' to 'avoid' then table is generated incorrectly.

I have taken the examples folder from your files and modified the examples.js file ([examples.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/2825699/examples.zip)
) from "examples.spans" function and if you open the demo you will see that the table is not generated correctly.

If you can please provide me a solution or a workaround.

Thanks in advanced!

**Comment by simonbengtsson** [comment] 2019-02-03 19:31
Hi! PR very much welcome fixing this 👍Here is the relevant code from the zip file:

```
examples.spans = function() {
    var doc = new jsPDF('p', 'pt');
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.setFontStyle('bold');
    doc.text('Rowspan and colspan', 40, 50);

    let body = bodyRows(1000);
    for (var i = 0; i < body.length; i++) {
        var row = body[i];
        if (i % 20 === 0) {
            row['id'] = {rowSpan: 50, content: i / 20 + 1, styles: {valign: 'middle', halign: 'center'}};
        }
    }
    let head = headRows();
    head[0]['id'] = {content: 'People', colSpan: 5, styles: {halign: 'center', fillColor: [22, 160, 133]}};

    doc.autoTable({
        startY: 60,
        head: head,
        body: body,
        theme: 'grid'
    });
    return doc;
};
```

**Comment by simonbengtsson** [comment] 2019-03-03 11:40
Duplicate of #461

**Closed by simonbengtsson** 2019-03-03 11:40 UTC
Labels: bug, help wanted
