### ISSUE TITLE
 line breaks are not working

### ISSUE THREAD

**Issue by loganscodes** [simonbengtsson/jsPDF-AutoTable#1040] opened 2024-02-26 21:54 UTC
When I justify the text, line breaks are not working. Here is my code.
```

doc.autoTable({
                theme:['grid'],
                startY:280,
                styles: {
                    fontSize:10,
                    textColor:80,
                    cellPadding:1,
                    /*rowHeight:700
                    /*font: 'arial'*/
                    halign: 'justify'
                },
                margin: margen,
                bodyStyles: {
                    valign: 'middle', //(doc.internal.getNumberOfPages()!=1) ? 'middle' : 'top',
                    cellPadding: 10,
                    lineColor:'#fff',
                    //rowHeight: (doc.internal.getNumberOfPages()==1) ? 700 : 'auto' ,
                },
                tableWidth: anchoTable,
                tableLineColor:'#fff',
                body: [[contenido]]
            })
```

**Comment by simonbengtsson** [comment] 2024-08-30 09:50
Likely duplicate of https://github.com/simonbengtsson/jsPDF-AutoTable/issues/974

**Closed by simonbengtsson** 2024-08-30 09:51 UTC
