### ISSUE TITLE
First row content missing when using a rowspan that breaks page

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [simonbengtsson/jsPDF-AutoTable#461] opened 2019-03-01 16:15 UTC
When a rowspan breaks through a page, the first row  is blank
https://glitch.com/edit/#!/prairie-park

**Comment by simonbengtsson** [comment] 2019-03-03 11:40
Duplicate of #446. But will keep this one open instead since better described.

**Comment by rong4188** [comment] 2019-04-03 23:34
Hi,
Does anyone get any fix or workaround on this?

Thanks,
Roni

**Closed** 2019-04-05 12:03 UTC
Labels: bug, help wanted

**Comment by simonbengtsson** [comment] 2019-04-05 12:08
Merged @rong4188 that might have fixed this. It's included in 3.1.1. Let me know if it works for you 👌
