### ISSUE TITLE
Wide Table (Not cell) will go beyond page width

### ISSUE THREAD

**Issue by echan7** [simonbengtsson/jsPDF-AutoTable#282] opened 2017-08-31 22:41 UTC
Hi I'm facing an issue that I don't understand how to solve, 
My table is currently too long/wide, not the cells, the entire table and I don't want it to go out of the page width. Instead i would like to split the table and move the overflowed part below the previous table. 

I tried setting tableWidth to the number I desire, but regardless of what option (wrap, auto) I choose or any number, it always go beyond the page. 

Any idea how to fix this? 

[letter (29).pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/1268688/letter.29.pdf)

**Comment by SaarthakSingh** [comment] 2017-09-11 10:13
Hi 

I am also facing a similar issue wide table getting cut from the right side.

Please let us know if it is fixable in any ways. 

Thanks

**Comment by simonbengtsson** [comment] 2017-09-11 10:16
I can't think of a way to do that in an easy way in the library today. One suggestion that might work for some people might be to choose a bigger document size and then split the pdf manually. Either letting the printer do this or in some other pdf manager library.

**Comment by SaarthakSingh** [comment] 2017-09-11 10:42
Thanks for Your Suggestion. 

Is there any ratio to find the width of the document so that content will be adjusted. I have tried by calculating with of dynamic content, But sometimes width is more or content gets scales automatically. 

Thanks

**Comment by simonbengtsson** [comment] 2017-09-11 13:11
What do you mean by ratio? Are you looking for the final content width of the pdf table?

**Comment by SaarthakSingh** [comment] 2017-09-18 11:51
HI 

Ratio means, Suppose content width 1100 px So, pdf width should be 100px more or 200. 

Is there any ratio to calculate the pdf width. 

Please let me know if you got my question.

Thanks

**Comment by SaarthakSingh** [comment] 2017-09-18 12:05
Bcoz as pdf size increases the content get shrink (font-size, width.. etc).

**Comment by simonbengtsson** [comment] 2018-08-04 13:17
Duplicate of #307

**Closed by simonbengtsson** 2018-08-04 13:17 UTC
