### ISSUE TITLE
overflow: 'linebreak' prevents table from automatically moving to the new page

### ISSUE THREAD

**Issue by hwkd** [simonbengtsson/jsPDF-AutoTable#373] opened 2018-07-24 00:13 UTC
I've been facing the issue as shown in the image and I couldn't find a solution. The cell isn't created around the content, and even if more rows are added, the rows overlap each other in the last row. If I remove the `overflow: 'linebreak'` from the options, it has no issues moving onto the next page. So I'm assuming there's a bug in calculating row height and trying to move to the new page when there's a linebreak.

Could somebody look into this issue?

![jspdf issue](https://user-images.githubusercontent.com/34149781/43109328-64b939cc-8f3a-11e8-8c7b-23afb512f996.png)

The option object is as follows in case it's relevant:
```
    {
      startY: this.pos.y,
      showHeader: 'firstPage',
      theme: 'grid',
      styles: {
        halign: 'center',
        textColor: 5,
        overflow: 'linebreak',
      },
      headerStyles: {
        fillColor: [255, 255, 255],
        textColor: [45, 45, 45],
        lineWidth: 1,
      },
      tableLineColor: 200,
      margin: { right: 70, top: 50, left: 70, bottom: 50 },
      columnStyles: {
        title: {
          fontStyle: 'bold',
          textColor: 5,
        }
      },
      columnStyles: {
        jobTitle: { fontStyle: 'bold' }
      }
    }
```

**Comment by AjayBKere** [comment] 2018-07-26 13:14
Can you share your code? so that I can help you.

**Comment by hwkd** [comment] 2018-07-29 07:40
I doubt it's my code that has an issue. I believe it's a bug in the library.

One solution I thought of is that if the library exposes a method for the user to set the y coordinate, I could probably use it to manually create a new page when it reaches a certain y coordinate of the current page and set the starting point of the new table row to the beginning of the new page.

However if this issue can be fixed without exposing such a method, it should be even better.
Please look into this issue soon as I am going into production and needs this to be fixed.

**Comment by simonbengtsson** [comment] 2018-08-04 12:09
Seems that there is a bug relating to page breaks since many people have reported it. Can you provide your code so that I can reproduce it?

**Comment by simonbengtsson** [comment] 2018-08-04 13:35
Duplicate of #370

**Closed** 2018-08-04 13:34 UTC
Labels: bug, needs information
