### ISSUE TITLE
How can I include this in an angular project? Will it be compatible with Typescript? 

### ISSUE THREAD

**Issue by samrantmedia** [simonbengtsson/jsPDF-AutoTable#294] opened 2017-11-01 11:14 UTC
Jspdf has types defined to make it compatible with typescript: 
https://stackoverflow.com/questions/41484323/how-to-use-jspdf-with-angular-2

Is there a way to make this library available for typescript?

**Comment by simonbengtsson** [comment] 2017-11-01 12:38
I remember researching this but got into troubles in the way the types at that time were defined for jspdf. It's kind of ironic if it is not possible to get type support for autotable considering it is written in typescript...

**Comment by samrantmedia** [comment] 2017-11-01 14:02
Yes that is odd. I started to look into it and thought that it looked to be written in typescript. I asked stackoverflow for help with this and they responded: 

https://stackoverflow.com/questions/47056473/how-to-write-a-typescript-definition-file-for-something-written-in-typescript?noredirect=1#comment81060096_47056473

Could you do something along the lines of: 

`tsc --declaration app.ts`

**Comment by simonbengtsson** [comment] 2017-11-01 15:06
Sure! Could you try it and let me know how it goes? If I remember correctly the problem is with the way jspdf's types are defined. See the link to an issue in typescript I added above. 

There are definitely workarounds, such as publishing another version of the jspdf types. Or submitting a pull request to that types. I have not gotten around to do that yet though.

**Comment by samrantmedia** [comment] 2017-11-01 16:09
Yeah, I will take a look!

**Comment by samrantmedia** [comment] 2017-11-02 09:56
I think in `main.ts `line 127 needs to be changed to: 
    `let header = tableElem.rows[0] as HTMLTableRowElement;`

and line 138 to be changed to: 
   ` let tableRow = tableElem.rows[i] as HTMLTableRowElement;`

only change is adding:` as HTMLTableRowElement`. Before it was complaining that it could not find 'cells' on Element. 

Then in htmlParser.ts, `RowResult` needs to be exported like so:
`export interface RowResult {`
This is because it is being used as a return type in one of the exported functions. 

Once this is done, 
tsc --declaration -p ./ --outDir dist/
 compiles and creates a set of definition files. I think the --module flag is needed to create the output as a single file, but this couldn't find the jspdf. I assume I am doing something wrong here. Which command were you using to publish?

**Comment by PrithiviRajG** [comment] 2018-01-26 11:20
@samrantmedia Did you able to solve the issue? do we have typescript definition?

**Comment by samrantmedia** [comment] 2018-01-26 11:36
@PrithiviRajG unfortunately not.

**Comment by PrithiviRajG** [comment] 2018-01-26 11:40
@samrantmedia Thanks for the quick reply :)
Is it possible to use this plugin without typescript definition?
Have you tried this https://github.com/simonbengtsson/jsPDF-AutoTable/issues/250

**Comment by simonbengtsson** [comment] 2018-10-28 18:54
Tried v3 now with angular without any issues so will close it. Basically just import jspdf and jspdf-autotable like this and use it as usual:

```
import jsPDF from 'jspdf'
import 'jspdf-autotable'
```

**Closed by simonbengtsson** 2018-10-28 18:54 UTC
Labels: enhancement
