### ISSUE TITLE
pageBreak bug

### ISSUE THREAD

**Issue by brandonguigo** [simonbengtsson/jsPDF-AutoTable#362] opened 2018-05-30 12:58 UTC
Hi, 

I have a table and I want to use this library to generate a pdf with only the checked elements of the table. 
I see for each rows of the table if the checkbox is checked, and I add it to the list of rows like in the example where columns have ids. (I have only one table)

My problem is the following one : When my rows are longer than the first page, all the rows stacks on top of the last one even when I've set pageBreak: 'always'... Do you have an idea on how to fix that ? 

Thanks

**Comment by simonbengtsson** [comment] 2018-08-04 12:15
Probably duplicate of #370. Will copy the jsfiddle to that issue.

**Closed by simonbengtsson** 2018-08-04 12:15 UTC
Labels: duplicate
